import type { LucideIcon } from '@/components/icons-map'

export const NAV_LINK_PERMISSIONS = [
  { id: "manage_admins", label: "Admin Staff Management", category: "Admin", href: "/dashboard/school-admin/manage-admin-staff" },
  { id: "manage_students", label: "Students", category: "Admin", href: "/dashboard/school-admin/students" },
  { id: "manage_teachers", label: "Teachers", category: "Admin", href: "/dashboard/school-admin/teachers" },
  { id: "manage_student_assignment", label: "Student Assignment", category: "Admin", href: "/dashboard/school-admin/student-assignment" },
  { id: "manage_teacher_assignment", label: "Teacher Assignment", category: "Admin", href: "/dashboard/school-admin/teacher-assignment" },
  { id: "manage_school_profile", label: "School Profile", category: "Admin", href: "/dashboard/school-admin/settings" },
  { id: "manage_classes", label: "Classes", category: "Academics", href: "/dashboard/school-admin/classes" },
  { id: "manage_subjects", label: "Subjects", category: "Academics", href: "/dashboard/school-admin/subjects" },
  { id: "manage_timetable", label: "Timetable", category: "Academics", href: "/dashboard/school-admin/timetable" },
  { id: "manage_grades", label: "Grading", category: "Academics", href: "/dashboard/school-admin/grading" },
  { id: "manage_attendance", label: "Attendance", category: "Academics", href: "/dashboard/school-admin/attendance" },
  { id: "manage_exams", label: "Exams", category: "Academics", href: "/dashboard/school-admin/exam" },
  { id: "view_performance", label: "Performance", category: "Results", href: "/dashboard/school-admin/performance" },
  { id: "export_results", label: "Export Results", category: "Results", href: "/dashboard/school-admin/results/export" },
  { id: "manage_report_templates", label: "Report Templates", category: "Results", href: "/dashboard/school-admin/results/templates" },
  { id: "manage_grading_policy", label: "Grading Policy", category: "Results", href: "/dashboard/school-admin/grading-policy" },
  { id: "manage_fees", label: "Manage Types", category: "Finance", href: "/dashboard/school-admin/manage-fees" },
  { id: "collect_fees", label: "Collect Fees", category: "Finance", href: "/dashboard/school-admin/collect-fees" },
  { id: "view_payments", label: "Payments", category: "Finance", href: "/dashboard/school-admin/payments" },
  { id: "manage_withdrawals", label: "Withdrawals", category: "Finance", href: "/dashboard/school-admin/withdrawals" },
  { id: "manage_expenses", label: "Expenses", category: "Finance", href: "/dashboard/school-admin/expenses" },
  { id: "view_fees", label: "Receipts", category: "Finance", href: "/dashboard/school-admin/receipts" },
  { id: "manage_transport", label: "Transport", category: "Operations", href: "/dashboard/school-admin/transport" },
  { id: "manage_hostel", label: "Hostel", category: "Operations", href: "/dashboard/school-admin/hostel" },
  { id: "manage_notices", label: "Announcements", category: "Communication", href: "/dashboard/school-admin/announcement" },
  { id: "send_messages", label: "Messaging", category: "Communication", href: "/dashboard/school-admin/messaging" },
  { id: "manage_news", label: "News", category: "Communication", href: "/dashboard/school-admin/news" },
  { id: "manage_materials", label: "Books", category: "Library", href: "/dashboard/school-admin/library/books" },
  { id: "manage_issued_books", label: "Issued Books", category: "Library", href: "/dashboard/school-admin/library/issued-books" },
  { id: "manage_library_categories", label: "Categories", category: "Library", href: "/dashboard/school-admin/library/categories" },
  // Admin Staff specific permissions
  { id: "view_admin_dashboard", label: "Dashboard", category: "Admin Staff", href: "/dashboard/admin-staff" },
  { id: "view_profile", label: "Profile", category: "Admin Staff", href: "/dashboard/admin-staff/profile" },
  { id: "view_permissions", label: "Permissions", category: "Admin Staff", href: "/dashboard/admin-staff/permissions" },
] as const;

export type PermissionId = (typeof NAV_LINK_PERMISSIONS)[number]['id'];

export const NAV_HREF_TO_PERMISSION: Record<string, PermissionId> = {
  "/dashboard/school-admin/manage-admin-staff": "manage_admins",
  "/dashboard/school-admin/students": "manage_students",
  "/dashboard/school-admin/teachers": "manage_teachers",
  "/dashboard/school-admin/student-assignment": "manage_student_assignment",
  "/dashboard/school-admin/teacher-assignment": "manage_teacher_assignment",
  "/dashboard/school-admin/settings": "manage_school_profile",
  "/dashboard/school-admin/classes": "manage_classes",
  "/dashboard/school-admin/subjects": "manage_subjects",
  "/dashboard/school-admin/timetable": "manage_timetable",
  "/dashboard/school-admin/grading": "manage_grades",
  "/dashboard/school-admin/attendance": "manage_attendance",
  "/dashboard/school-admin/exam": "manage_exams",
  "/dashboard/school-admin/performance": "view_performance",
  "/dashboard/school-admin/results/export": "export_results",
  "/dashboard/school-admin/results/templates": "manage_report_templates",
  "/dashboard/school-admin/grading-policy": "manage_grading_policy",
  "/dashboard/school-admin/manage-fees": "manage_fees",
  "/dashboard/school-admin/collect-fees": "collect_fees",
  "/dashboard/school-admin/payments": "view_payments",
  "/dashboard/school-admin/withdrawals": "manage_withdrawals",
  "/dashboard/school-admin/expenses": "manage_expenses",
  "/dashboard/school-admin/receipts": "view_fees",
  "/dashboard/school-admin/transport": "manage_transport",
  "/dashboard/school-admin/hostel": "manage_hostel",
  "/dashboard/school-admin/announcement": "manage_notices",
  "/dashboard/school-admin/messaging": "send_messages",
  "/dashboard/school-admin/news": "manage_news",
  "/dashboard/school-admin/library/books": "manage_materials",
  "/dashboard/school-admin/library/issued-books": "manage_issued_books",
  "/dashboard/school-admin/library/categories": "manage_library_categories",
  // Admin Staff routes
  "/dashboard/admin-staff": "view_admin_dashboard",
  "/dashboard/admin-staff/profile": "view_profile",
  "/dashboard/admin-staff/permissions": "view_permissions",
} as const;

